### ISSUE TITLE
MBTI - Before Homepage Making

### ISSUE THREAD

**Issue by JOO05** [JOO05/MBTI#1]
> A journey of a thousand miles starts with one step.

**ToDo List**
- [x] add page folder
- [x] add Home.js, Question.js, Result.js file
- [x] remove App.css and modify App.js
- [x] connect home.js and app.js

[https://opentheway.tistory.com/41](url)
