### ISSUE TITLE
MBTI - Homepage Making

### ISSUE THREAD

**Issue by JOO05** [JOO05/MBTI#2]
**ToDo List**

- [x] install and import styled-components
- [x] import bootstrap in html, js
- [x] make asset folder and add picture
- [x] import image and bootstrap button
- [x] make structure and apply css to each part(styled-components)

[https://opentheway.tistory.com/41](url)
