### ISSUE TITLE
MBTI - Page Routing

### ISSUE THREAD

**Issue by JOO05** [JOO05/MBTI#3]
**ToDo List**
- [x] install Router
- [x] modify index.js & App.js to import Router
- [x] make fonts folder and put ttf file in it
- [x] make App.css and apply font
- [x] apply font at Home.js
- [x] import useNavigate function
- [x] define handleClickButton

[https://opentheway.tistory.com/42](url)
