### ISSUE TITLE
MBTI - Making Question Page

### ISSUE THREAD

**Issue by JOO05** [JOO05/MBTI#4]
**ToDo List**

- [x] apply styled-component & use wrapper
- [x] apply progress bar
- [x] change the alignment of buttons
- [x] make exam paper

[https://opentheway.tistory.com/43](url)
