### ISSUE TITLE
MBTI - Completing Test Logic

### ISSUE THREAD

**Issue by JOO05** [JOO05/MBTI#5]
**ToDo List**

- [x] manage process bar
- [x] make the values change and accumulate each time I click a button
- [x] use map functions to simplify code
- [x] create a code to move to the results page when I click the answer in the last question

[https://opentheway.tistory.com/44](url)
