### ISSUE TITLE
MBTI - Making Result Page

### ISSUE THREAD

**Issue by JOO05** [JOO05/MBTI#6]
**ToDo List**

- [x] put prepared data into resultdata.js
- [x] make image folder(mbtis) in assets folder
- [x] import resultdata.js to Result.js
- [x] modify some code in Result.js so that it contains data from resultdata.js
- [x] set onClick event to return Home.js

[https://opentheway.tistory.com/45](url)
