### ISSUE TITLE
MBTI - Completing Result Logic

### ISSUE THREAD

**Issue by JOO05** [JOO05/MBTI#7]
**ToDo List**

- [x] create an expression to derive MBTI based on the value calculated in the Question.js file
- [x] search about map() and reduce()
- [x] Match MBTI value with actual result data and show it
